### ISSUE TITLE
I wonder if this could be modded further.

### ISSUE THREAD

**Issue by Aasikki** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#12]
This is a bit unrelated, sorry about that, can't think of other place to post this.

I wonder if this app could be also modified to work on a wear os watch. It already seems to work when I sideloaded it to my watch, but the ui doesn't fit on the screen so I can't connect to my scooter.

**Comment by BenjaminSoelberg** [comment]
Sorry no. Only if Wilfa makes a watch app. I'm just patching the existing android app.
