### ISSUE TITLE
Firmware V1. 31

### ISSUE THREAD

**Issue by Melotron** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#14]
Is there any way to change the speed on firmware v1.31.
I updated the firmware by mistake.

Even with a gps hack so are the scooter locked to 20km/h.

**Comment by BenjaminSoelberg** [comment]
In fact I really could use a few beta testers

**Comment by bmbdk** [comment]
Hi
As I can see from ealier conversations, you live in Copenhagen? I can get you access to a physical scooter there. However, I live in another part of Denmark and do have some background knowledge that might be helpful for testing.

**Comment by BenjaminSoelberg** [comment]
That is true. I'm not sure if I understood: Would you be able to give me physical access to a scooter with firmware 1.31 on it ?

**Comment by Melotron** [comment]
Sure. I can be a beta tester.
What would you want me to do?

**Comment by Melotron** [comment]
I think the speed lock are in the firmware.
Ive set the location to Finland on my GPS and the max speed are showing as 25km/h in the app, but the scooter won't go faster then 20km/h.

I can take a few screenshots on it later today.

**Comment by bmbdk** [comment]
> That is true. I'm not sure if I understood: Would you be able to give me physical access to a scooter with firmware 1.31 on it ?

Yes, in Copenhagen I can

**Comment by BenjaminSoelberg** [comment]
@Melotron I suspect that you are right. But I'll give it a go anyway.

**Comment by BenjaminSoelberg** [comment]
Try this version, please note that it is completely untested.
https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/raw/main/EWay_Scooter_v1.2.03_speed.apk

**Comment by Melotron** [comment]
Ive tested the new software, but it's the same. 

![Screenshot_20230518_142924_Eway Scooter](https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/assets/13728029/a3ea6318-4670-4757-8ea7-4db86477df7b)
Here are the speed settings. 

![Screenshot_20230518_142942_Eway Scooter](https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/assets/13728029/9da2d68c-4cb6-409d-bf32-dab505770493)
But when I go back to the home screen it stills say Sweden 20km/h.

Ive also tired a GPS hack with your new app, and it's the same.

**Comment by Melotron** [comment]
Sorry, I pressed the wrong button 😂😂😂

**Comment by Melotron** [comment]
I cant locate the firmware or the apps location in /android/data.
Ive also removed the original app and installed your app, so the firmware might to total gone from my phone.

**Comment by BenjaminSoelberg** [comment]
I'll try and make a patch that downloads the firmware and don't delete it after.

**Comment by Melotron** [comment]
The speed are caped at 20km. Tested it a few times on my to work.
I also tried with the GPS hack, and it's still caped at 20km.
So it feels as the limitations are in the firmware.

**Comment by larswibier** [comment]
I was able to roll back the firmware of my E-600 MAX to 1.26 after accidentally upgrading to 1.31 through an old version of the KingSong "Soft Tuner" app (version 139).
You can find it here: https://mega.nz/file/ndZ2VbaR#sw9NYqnkG4t2a4pftiepBA3-JP2GhbtaXEmvCAnOYgY
Only give the app location access, the rest is not needed.
The app will give you trouble logging in, so what you can do is after pressing "login as guest", immediately disable Wi-Fi/mobile data. That way the app cannot communicate with the server and kick you out. Then connect to your scooter.
After that, press on "Firmwaer update" (no, that's not a typo on my end), and connect to Wi-Fi/mobile data again.
Then you'll get a list of previous firmwares. Select the one you want to use, and then press "update firmware". The app will give you a warning that you're downloading a previous firmware, just press "OK".
This way I was able to get the speedhack working again, as it seems that the 20km/h limit is in the 1.31 firmware, and I assume that it is difficult to remove.

**Comment by Melotron** [comment]
@larswibier THANK YOU SO MUCH!
It worked to roolback the firmware.
I was just outside and took it for a spin. Got up to 22km on the first test outside work.
I can try to download the firmwares, but the best solution are to have this as solution if you update the firmware. And use the the hacked app as speed setter. 

Also thanks alot to @BenjaminSoelberg for all his work with it.

**Comment by bmbdk** [comment]
This is a great tip, thank you @larswibier 
The timing of not being kicked out when logging in as guest is a bit tricky - after numbers of failed attempts, I made it work by only having wifi data on the phone and pull the network plug on my router when logging in ;) Now firmware is downgraded to 1.26

Also many thanks to @BenjaminSoelberg for the updated APP that now works flawless setting the speed limit

**Comment by BenjaminSoelberg** [comment]
@RZG0 After looking into the APP all i can say is that they track you in every way they can. To be honest I would do the same if I could. The more data you have the better informed you can be about everything from marketing/targeting and reliability and production issues.

**Comment by RZG0** [comment]
Yea exactly. I tries to downgrade to 1.26 and it worked. Now i can get up to 34-36km on level ground. And your app works well aswell. Gona keep it topped max at 30.

**Comment by BenjaminSoelberg** [comment]
I have created a new version which is available here: https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/raw/main/EWay_Scooter_v1.2.03_speed.apk

It still do not have any fix for newer firmwares but read above on how to downgrade.
I have reworked the speed selection engine and it should work better now.
I will work on a way to downgrade from within the app and I'll try to remove unneeded permissions and "newer version" alert boxes

Give it a go and report back thanks.

**Comment by RZG0** [comment]
Installed, will test on next drive, it would be good to have option change speeds on different modes so in finland i would have 10/25/unlimited

**Comment by BenjaminSoelberg** [comment]
@RZG0 I try not to change the original app too much (as it is hard to maintain patches). But I think you can mix both max speed and gear settings (P1/P2/P3) to get what you ask for.

**Comment by BenjaminSoelberg** [comment]
@all I have concluded that the firmware is encrypted and only decrypted by the scooter after updating as there is no code in the APP that does the decryption. So there is currently no to me known way to fix the firmware in v1.31. This means that the only way to fix the speed lock issue is to downgrade. But i did manage to grab a copy of the firmware "2021-08-11-07-17-04.bin" which i believe to be v1.26. So i could patch the app to use that. But I don't know if this firmware works on other scooters than e-way e-350.

**Comment by BenjaminSoelberg** [comment]
@RZG0 @Melotron @bmbdk @larswibier I have patched the KingSong SoftTuner so you don't have to do the awkward / difficult trick with wifi on/off. So you guys should be able to use the KingSong SoftTuner to downgrade at will. Also it seems like only v131 & v126 of the firmware are available for actual installation. Give it a go: https://github.com/BenjaminSoelberg/kingsong-soft-tuner-hack

**Comment by BenjaminSoelberg** [comment]
This also concludes this issue and we can finally close it
