### ISSUE TITLE
Problems with scooter turning off and won't start

### ISSUE THREAD

**Issue by LinusOnTheGo** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#19]
Hi,

Thanks for the solution to get my E-350 go a little faster. Tried it on the first version and it worked fine a couple of days. Then the scooter randomly died when i drove it and it would not start after. I had to wait a few hours for it to start, connecting charger wont do it either.

After a few weeks I got back to the original Wilfa-app and set the speed to 20km/h **(is this how to reverse it to previous state?)**  and i tough it was fine. I was wrong. Still randomly dies and something in the morning it wont even start, if i try later in the day it starts. Very randomly.

Link to screen-shot from faultlist. Does anyone know whats broken and how to fix it? Have a reversed it to original the wrong way?

I did upgrade the original firmware now but still same problems:
Firmware model: EWAY-XL
Version: 1.31 

Yeah, I know what game I was playing when trying it out so the damage may be done already but I still have some hope.. :-)

Thanks in advance!

[https://imgur.com/a/o1zjq0l](url)

**Comment by BenjaminSoelberg** [comment]
It sounds like that your scooter just can’t handle the current needed by the higher speed. It could be a number of things from a loose wire to something more catastrophic. And yes it reverts to the default speed when running the original app. I would return it if you still have a warranty. Else take the screws off the bottom and see if you can find the fault in the speed controller. One user have a e350 and it have been driving more than 2600km with the speed mod. But which version do you have ?Mvh / Best regardsBenjamin SølbergDen 30. maj 2023 kl. 08.12 skrev Linus Karlsson ***@***.***>:﻿
Hi,
Thanks for the solution to get my E-350 go a little faster. Tried it on the first version and it worked fine a couple of days. Then the scooter randomly died when i drove it and it would not start after. I had to wait a few hours for it to start, connecting charger wont do it either.
After a few weeks I got back to the original Wilfa-app and set the speed to 20km/h (is this how to reverse it to previous state?)  and i tough it was fine. I was wrong. Still randomly dies and something in the morning it wont even start, if i try later in the day it starts. Very randomly.
Link to screen-shot from faultlist. Does anyone know whats broken and how to fix it? Have a reversed it to original the wrong way?
Yeah, I know what game I was playing when trying it out so the damage may be done already but I still have some hope.. :-)
Thanks in advance!
https://imgur.com/a/o1zjq0l

**Comment by tnfno** [comment]
Probably not related to this hack.  Things do go wrong, but I guess you in Sweden as well has good consumer laws so you will get it fixed/replaced for free as long as it is not too old.  JUst remove the hack first ;)
