### ISSUE TITLE
Anyone know to get hands on the ks pl 1.20 firmware for my e-way e500 scooter?

### ISSUE THREAD

**Issue by Xiuyju** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#21]
Does anyone know how to get hands on the ks-pl 1.20 firmware version for my e-way e500 that it came with updated it to 1.31 with SoftTuner that is on ios but i cant downgrade it anymore because the firmware version link dosent exist anymore?

**Comment by BenjaminSoelberg** [comment]
Im sorry I don't have a scooter to test on. I need to have access to one to find a solution. I live in Copenhagen, Denmark btw.
