### ISSUE TITLE
E way 6075frs

### ISSUE THREAD

**Issue by Delitow** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#28]
Hi! 
I have kingsong tuner 1.3 version and cant get 1.2 back! I already had 1.2 but accidentally pressed update. I deleted it, downloaded it again and got the 1.3 version. Does anyone know how to get the 1.2 version back? benjamin 1.3 patched version didnt work. Now my scooter go max 25km/h.

**Comment by BenjaminSoelberg** [comment]
I'm sorry to hear that. I unfortunately don't have access to a scooter to test on.
