### ISSUE TITLE
Problem med installationen

### ISSUE THREAD

**Issue by DavidQvist06** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#3]
Jeg har nu downloaded filen, og når jeg så prøver at åbne og den så spørger om den skal installeres til E-Way, så siger jeg ja og den går i gang.. kort tid efter får jeg så en besked om det ikke var muligt at installere den til appen - Hvad jan jeg gøre her? 
Har en Samsung Galaxy A42

**Comment by BenjaminSoelberg** [comment]
Prøv nyeste version hvor et problem med manglende zipalign er løst.
Se https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/issues/1
