### ISSUE TITLE
With scooter hacking you can adjust voltage and ampers wich is risky but mine is eway 600 max and max speed this way is 37 km/h and its 53.5vdc. so script what gives max voltage like 1,5v more and few amps more. I have voi scooter  controlbox so i should use it but hard to get it code opened. Same i have the back wheel and theyr 2 years at least old but so good. Have heard it goes 90 km/h... So just put voltage/A regulator from ebay? Then i want that program in my screen, how...

### ISSUE THREAD

**Issue by Buusis** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#30]

**Comment by BenjaminSoelberg** [comment]
I have no idea sorry. Seems like a big project.

**Comment by Buusis** [comment]
Mine goes 38 km/h but why weaker eway e-600 (non-max) goes slower than normal 600?
Normal 600 goes 44 or so.... Battery i guess. Or is it wire restricted? Or have they made it "heavyer" magnetig field so there is more torque... Originally this went 45km/h. And i use ur eway software to get unlimited and soft tuner for everything else but wit what program i check voltage becs it shows full 51.2volts. the i have voi scooters motor and box but maybe just the wheel change...?

LähetettyOutlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Buusis** [comment]
Mine doesnt show on scooter hacking

LähetettyOutlook for Android<https://aka.ms/AAb9ysg>
________________________________
