### ISSUE TITLE
Not working on newer phones

### ISSUE THREAD

**Issue by Pentakim** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#4]
Cant be installed on Samsung Galaxy Fold 3

**Comment by BenjaminSoelberg** [comment]
Might finally be fixed, try the latest version and report back :-)

**Comment by BenjaminSoelberg** [comment]
See https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/issues/3
