### ISSUE TITLE
Firmware version 1.26 needs patching too

### ISSUE THREAD

**Issue by st-hansdraugen** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#5]
Getting ready for the spring :-)
Using E-600MAX-976
Eway Scooter app just uploaded new firmware to the scooter. New app was automatically installed a while ago.
Current version now reported as V1,26

**Comment by BenjaminSoelberg** [comment]
Does this mean that the hack no longer works ?

**Comment by st-hansdraugen** [comment]
It does not work. I have not tried with earlier versions (older app) so I can not comment on "no longer".
Tried to download

**Comment by st-hansdraugen** [comment]
[EWay_Scooter_v1.0.15_speed.apk](https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/raw/main/EWay_Scooter_v1.0.15_speed.apk)
as per the README.me text. Got message that it would install as a font. No errors, no change in speed setting in app.
Enabled developer mode. Chose Install. Message: App was not installed. No change in speed setting in app.

**Comment by gimzors** [comment]
Hi i have the same problem with E-600MAX-976  version
V1,26. App is working exept Speed changing.

**Comment by BenjaminSoelberg** [comment]
I really need access to another scooter to fix the speed limit on newer firmwares.
If you guys live in Denmark and would be able share one for a few days only then would I be able to help with the new versions.
The scooter I used to test the current version is no longer available to me.

**Comment by st-hansdraugen** [comment]
Too far away for physical access unfortunaltely.

**Comment by MozartWolfgang** [comment]
> I really need access to another scooter to fix the speed limit on newer firmwares. If you guys live in Denmark and would be able share one for a few days only then would I be able to help with the new versions. The scooter I used to test the current version is no longer available to me.

Where in Denmark are you located for the E-way E600 MAX ?

**Comment by BenjaminSoelberg** [comment]
I am located in copenhagen, would you be able to lent me a scooter for a few days ?

**Comment by Sembach** [comment]
Hi
I have a E-way E600 MAX  with version 1.26
I may be able to lend you mine, i live about an hour from copenhagen by train.

I have tried to install your app but with no luck

EDIT I just installed your new release and  it worked, i can now choose unlimited and lifting the wheel gets me to 38 kmph

**Comment by BenjaminSoelberg** [comment]
Fantastic news!

I was looking into the new version of the app and couldn't really see why it shouldn't work either.

Good to hear that i works with firmware 1.26 as well.
I'll write that into the README as well.

Have fun and please for the love of god, wear a helmet!!!!

**Comment by sjm42** [comment]
Well, I just installed this on a OnePlus 11 phone running Android 13 and the hacked app installs and works fine.
I am not able to actually try riding my E600 MAX because it's still ice and snow outside (I live in Finland).
The speed limit thing _seems_ to work, though.

**Comment by greengarlic** [comment]
Looks like the app/bluetooth connection does not work on Android 8.0. The same with the original E-Way Scooter app. Got this working on another old phone with Android 9 and E600 with firmware 1.26. No more speed limiter. While my top speed is little over 30km/h this made me wear helmet _every_ _time_. Thank you!

The original E-Way app wanted to update 1.26 firmware to newer version but I obviously skipped.

**Comment by RedSweGaming** [comment]
So is there someway to install an older firmware? 

My E600 is sadly running on 1.32 or something and i have no clue how to get an older version, if its even possible.

**Comment by BenjaminSoelberg** [comment]
@RedSweGaming I'm working on a new version. Keep looking for updates.

**Comment by RedSweGaming** [comment]
@BenjaminSoelberg How is your work progressing?

**Comment by Mortenton** [comment]
Any fix for speed hack for e-way-e500? Only 20 kmt. In Sweden now,but live
in Norway. 25-30 would be great 😊 tried the eway app,but only 20kmt max.
Also tried vpn set to Finland. Network error. Any tips?
Morten

ons. 26. jul. 2023, 13:05 skrev RedSweGaming ***@***.***>:

**Comment by nahkavelho** [comment]
any idea to get 6075 fsr working? stuck on 1.31 firmware

**Comment by NukerbSZ** [comment]
Same, stuck in ks-ps 1 31. Need to downgrade but can't find older firmware anywhere.

**Comment by JupatusPrime** [comment]
I have e-way e350. When i download 1.26 version for unlimited speed.  My scooter dosnt work. It just flashes CH and UP
