### ISSUE TITLE
New scooter not able to connect

### ISSUE THREAD

**Issue by CodeCrawlerA** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#6]
I got the E-way E600Max scooter, installed your app, and the app connected to the scooter and everything worked as described. However, there were a few quality issues with the scooter, so I had to get a replacement (same model). But the app is unable to find the new scooter. The original Wilfa app does find it (as "E-600MAX-26334") and connects, so there is no problem with the BT connectivity. In the original app I can see that the scooter runs v1.20 of the firmware (I have not upgraded to 1.26), which is the same as the last scooter did, I think. How can I get the app to connect to the new scooter?

Also, I would request a speed limit option of about 32 km/h (= 20 mph). This equals the "US" mode of the Ninebot G30 MAX, which seems to be a reasonable speed for the scooter hardware. Unlimited (about 40 km/h) feels a bit too fast and unsafe, and 25 a bit too slow.

**Comment by BenjaminSoelberg** [comment]
You can try at see if the original version (1.0.15) of the app (provided within this repository) works with your scooter.
If it does then my unrestricted version should as well. Can you try that first ?

The different speed limits seems to be hard coded within the firmware so I am unable to select other kinds at the moment.

**Comment by BenjaminSoelberg** [comment]
I suggest uninstalling any eway apps you have and then try my new patched version again and report back if .
Take a look at https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/releases/tag/1.0.15.5

Have fun and please report any further issues.
You can just reopen the issue if it is still a problem.
