### ISSUE TITLE
Does't work

### ISSUE THREAD

**Issue by LennartKnarvik** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#8]
Hi!

Super happy with the app, Have used it since March on my Samsung S9 running android 10 UI-version 2,5, and it works perfectly every time except i think it's clocking wrong KM on the odometer(trip meter) no issue TBH
Unfortunately when reciving my new phone Samsung S22 running Android 12 UI 4.1, I'm not able to install it due error messages. 
Yes phone is in developer mode.

Best regards Lennart Knarvik

**Comment by mathias7799** [comment]
I have the same issue. 
Samsung FE20 5G Android vers. 12

**Comment by LahikaupanAsko** [comment]
I have OnePlus Nord N10 5G Android 11, when I try install pack my phone's shows messages: E Way scooter The application was not installed. Can you help me ?

**Comment by dogematti** [comment]
Same error here on android 11.

Is there a specific android version that must be used? 

Does the phone have to be rooted?

It would be awesome if this could be fixed.

**Comment by BenjaminSoelberg** [comment]
Fixed

Take a look at https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/releases/tag/1.0.15.5

Have fun and please report any further issues.
