### ISSUE TITLE
Android 12 issue? "Appen blev ikke installeret, da pakken lader til at være ugyldig" (App not installed as package appears to be invalid)

### ISSUE THREAD

**Issue by JRGaarde** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#9]
Unable to install Eway_Scooter_v1.0.15_speed.apk on Samsung S20 Android 12. Getting "Appen blev ikke installeret, da pakken lader til at være ugyldig" (App not installed as package appears to be invalid).

- Developer mode enabled, Chrome allowed to install
- Tried uninstalling all E-ways apps, rebooting and installing. same error

Could this be caused by new restrictions/demands in Android 12. IE. https://stackoverflow.com/questions/71022310/android-12-apk-throws-invalid-package-upon-install

**Comment by jacktinuss** [comment]
Same for me! Samsung S21.

Appen blev ikke installeret, da pakken lader til at være ugyldig

**Comment by MuscularAss69** [comment]
I have E-way E6075FRS scooter and unlimited speed doesn't work. Scooter firmware is v1.31.

**Comment by BenjaminSoelberg** [comment]
I'll look into this again. Sorry for all the problems. I actually don't own newer android which makes it a little like a guessing game.

**Comment by BenjaminSoelberg** [comment]
Fixed

Take a look at https://github.com/BenjaminSoelberg/wilfa-e-way-electric-scooter-hack/releases/tag/1.0.15.5

Have fun and please report any further issues.

**Comment by MuscularAss69** [comment]
Hello! I use this and still max speed is 25km/h?

pe 23. syysk. 2022 klo 20.34 Benjamin Sølberg ***@***.***>
kirjoitti:

**Comment by MuscularAss69** [comment]
My friend have same scooter but it has fw 1.26 and run 40km/h. I have fw
1.31 and doesn't work.🤦🏻😅

pe 23. syysk. 2022 klo 20.44 Tomi Leppäkynnäs ***@***.***> kirjoitti:

**Comment by BenjaminSoelberg** [comment]
Have you tried the latest version I have just released ?

**Comment by BenjaminSoelberg** [comment]
And please create a new issue where you describe what version you have tried and what firmware version you have and I'll look into it.

**Comment by MuscularAss69** [comment]
Yes

pe 23. syysk. 2022 klo 22.58 Benjamin Sølberg ***@***.***>
kirjoitti:

**Comment by MuscularAss69** [comment]
I tried android 11 phone and same thing.

pe 23. syysk. 2022 klo 18.47 Benjamin Sølberg ***@***.***>
kirjoitti:

**Comment by BenjaminSoelberg** [comment]
@MuscularAss69 Can I get you to create a new issue this issue was already solved?

**Comment by JRGaarde** [comment]
I can confirm version 1.0.15.5 works on Android 12 with firmware 1.26

**Comment by JRGaarde** [comment]
And thanks 🥇

**Comment by MuscularAss69** [comment]
I must downgrade my scooter. Is that possible anyhow?

ke 28. syysk. 2022 klo 9.43 JRGaarde ***@***.***> kirjoitti:

**Comment by BenjaminSoelberg** [comment]
> And thanks 🥇 

You are welcome😁 
Stay safe and wear a helmet
